apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  replicas: 2
  template:
    metadata:
      labels:
        service: backend-user
    spec:
      containers:
      - image: sakshee19/udacity-user-service:1.0.0
        name: backend-user 
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"      
        env:
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: postgres-port
              key: POSTGRES_PORT
        - name: POSTGRES_DIALECT
          valueFrom:
            configMapKeyRef:
              name: postgres-dialect
              key: POSTGRES_DIALECT
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: url
              key: URL
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: jwt-secret
              key: JWT_SECRET
        - name: POSTGRES_DATABASE
          valueFrom:
            configMapKeyRef:
              name: postgres-database
              key: POSTGRES_DATABASE
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: postgres-host
              key: POSTGRES_HOST
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_USERNAME
      # restartPolicy: Always